// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzspJoYuFCClJJXpaoN8IvTH1Pv1fdWHY',
    appId: '1:718315241726:android:d1346b83e767eca84965af',
    messagingSenderId: '718315241726',
    projectId: 'todo-app-58f6e',
    storageBucket: 'todo-app-58f6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ScsiOtb9uTRzZa8du9OjhjWb_vtcM1E',
    appId: '1:718315241726:ios:69b4d746c7d975194965af',
    messagingSenderId: '718315241726',
    projectId: 'todo-app-58f6e',
    storageBucket: 'todo-app-58f6e.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6D9GF6owJtdk_jVXwjA0OP1KgRyIqygI',
    appId: '1:718315241726:web:98930f5d9ad0a27d4965af',
    messagingSenderId: '718315241726',
    projectId: 'todo-app-58f6e',
    authDomain: 'todo-app-58f6e.firebaseapp.com',
    storageBucket: 'todo-app-58f6e.appspot.com',
  );
}
